# Generated by Django 4.2.3 on 2024-02-22 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiment', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
                ('supervisor', models.CharField(max_length=200)),
                ('analysis_type', models.CharField(choices=[('kinetic parameters estimation', 'kinetic parameters estimation'), ('medium composition optimization', 'medium composition optimization')], max_length=200)),
                ('observations', models.TextField(blank=True, null=True)),
                ('experiments', models.ManyToManyField(to='experiment.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisKineticParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=200)),
                ('parameter_units', models.CharField(max_length=200)),
                ('observations', models.TextField()),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=200)),
                ('variable_units', models.CharField(max_length=200)),
                ('variable_type', models.CharField(choices=[('discrete', 'discrete'), ('continuous', 'continuous')], max_length=200)),
                ('observations', models.TextField()),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisVariableValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('value_type', models.CharField(choices=[('lower', 'lower'), ('upper', 'upper'), ('average', 'average'), ('deviation', 'deviation'), ('optimal', 'optimal')], max_length=200)),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisvariable')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisKineticParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('value_type', models.CharField(choices=[('lower', 'lower'), ('upper', 'upper'), ('average', 'average'), ('deviation', 'deviation'), ('optimal', 'optimal')], max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysiskineticparameter')),
            ],
        ),
    ]
