# Generated by Django 4.2.3 on 2024-02-22 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microorganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('optimal_conditions', models.TextField()),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(max_length=200)),
                ('market_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('detection_method', models.CharField(max_length=200)),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('observations', models.TextField()),
            ],
        ),
    ]
